// frontend/src/components/shared/ContactLink.tsx
import { CSSProperties, FC, useState } from 'react';

export type LinkType = 'email' | 'phone';

interface HeaderProps {
  cc?: string;
  bcc?: string;
  subject?: string;
  body?: string;
  [index: string]: string | undefined;
}

interface ContactLinkProps {
  type: LinkType;
  href: string;
  title: string;
  header?: HeaderProps;
  style?: CSSProperties;
}

const ContactLink: FC<ContactLinkProps> = (props) => {
  const [humanInteractionState, setHumanInteractionState] = useState(false);

  const handleCopiability = () => {
    setHumanInteractionState(true);
  };

  const createContactLink = (props: ContactLinkProps) => {
    const combinedHeader =
      props.header &&
      Object.keys(props.header)
        .map((key) => `${key}=${encodeURIComponent(props.header![key]!)}`)
        .join('&');

    let link = 'mailto:' + (props.header ? `${props.href}?${combinedHeader}` : props.href);
    if (props.type === 'phone') link = 'tel:' + props.href;

    return link;
  };

  const reverse = (stringToReverse: string) => {
    return stringToReverse.split('').reverse().join('').replace('(', ')').replace(')', '(');
  };

  const directionStyle: CSSProperties = {
    ...(props.style || {}),
    unicodeBidi: 'bidi-override',
    direction: humanInteractionState ? 'ltr' : 'rtl',
  };

  const renderProps = {
    onFocus: handleCopiability,
    onMouseOver: handleCopiability,
    onContextMenu: handleCopiability,
    href: humanInteractionState === true ? createContactLink(props) : 'obfuscated',
    title: props.title,
    style: directionStyle,
  };

  return <a {...renderProps}>{humanInteractionState ? props.href : reverse(props.href)}</a>;
};

export default ContactLink;

// src/components/ContactLink.svelte
<script lang="ts">
	import type { Snippet } from "svelte";
	import type { HTMLAnchorAttributes } from "svelte/elements";
	import type { Protocol } from "@/types/url";

	interface ContactLinkProps extends HTMLAnchorAttributes {
		protocol: Protocol;
		header?: {
			[index: string]: string | undefined;
			bcc?: string;
			body?: string;
			cc?: string;
			subject?: string;
			text?: string;
		};
		href: string;
		children?: Snippet;
		title: string;
	}

	function reverse(stringToReverse: string): string {
		return [...stringToReverse]
			.toReversed()
			.map((char) => {
				if (char === "(") return ")";
				if (char === ")") return "(";
				return char;
			})
			.join("");
	}

	function createContactLink({
		protocol,
		header,
		href,
	}: Pick<ContactLinkProps, "protocol" | "header" | "href">): string {
		const combinedHeader =
			(header &&
				Object.keys(header)
					.map((key) => `${key}=${encodeURIComponent(header[key] ?? "")}`)
					.join("&")) ||
			"";

		const link = protocol + href;

		if (protocol === "mailto:") {
			return header ? `${link}?${combinedHeader}` : link;
		}

		if (protocol === "tel:") {
			return link.replaceAll(/\s/g, "");
		}

		return link;
	}

	let { children, header, href, protocol, style, ...props }: ContactLinkProps =
		$props();

	let hasInteracted = $state(false);

	const hrefText = $derived(href.slice(Math.max(0, href.indexOf(":") + 1)));

	const handleInteraction = () => {
		hasInteracted = true;
	};

	const directionStyle = $derived(
		[
			style,
			`direction: ${children || hasInteracted ? "ltr" : "rtl"}`,
			"unicode-bidi: bidi-override",
		]
			.filter(Boolean)
			.join("; "),
	);

	const handleClick = (event: MouseEvent) => {
		if (!hasInteracted) {
			event.preventDefault();
			hasInteracted = true;
		}
	};

	const handleKeyDown = (event: KeyboardEvent) => {
		if (event.key === "Enter" || event.key === " ") {
			handleInteraction();
		}
	};

	const computedHref = $derived(
		hasInteracted ? createContactLink({ protocol, header, href }) : "#",
	);
	const computedAriaLabel = $derived(
		hasInteracted ? undefined : "Kontaktlink - tippen zum Anzeigen",
	);
	const computedRole = $derived(hasInteracted ? "link" : "button");
	const displayText = $derived(hasInteracted ? hrefText : reverse(hrefText));
</script>

<a
	{...props}
	aria-label={computedAriaLabel}
	href={computedHref}
	onclick={handleClick}
	oncontextmenu={handleInteraction}
	onfocus={handleInteraction}
	onkeydown={handleKeyDown}
	onmouseover={handleInteraction}
	ontouchstart={handleInteraction}
	role={computedRole}
	style={directionStyle}
>
	{#if children}
		{@render children()}
	{:else}
		{displayText}
	{/if}
</a>
